config/routes.rb
MusicBand::Application.routes.draw do
  get "pages/welcome"

  resources :publications

  namespace :admin do
    resources :publications
    root 'publications#index'
  end

  root 'pages#welcome'

end

app/models/publication.rb
class Publication < ActiveRecord::Base

  # Manage thumbnail image file
  has_attached_file :thumbnail,
    storage: :dropbox,
    dropbox_credentials: Rails.root.join("config/dropbox.yml")

  # Convert the publication markdown content into HTML
  def to_html
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true)
    html = markdown.render(content)
    html = markdown_extention_youtube_links(html)
    return html.html_safe
  end

  private

  # Markdown extention: replace every youtube links with embedded youtube video
  def markdown_extention_youtube_links(html)
    html = html.gsub /<a\shref="http:\/\/www\.youtube\.com\/watch\?v=(.*).*".*>.*<\/a>/o, 
      "<p><iframe class=\"youtube-player\" src=\"http://www.youtube.com/embed/\\1\"></iframe></p>"
    return html
  end
end

app/controllers/admin/publications_controller.rb
class Admin::PublicationsController < ApplicationController
  before_action :set_publication, only: [:edit, :update, :destroy]

  def new
    @publication = Publication.new
  end

  def edit
  end

  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_path(@publication), notice: 'Publication was successfully created.' }
        format.json { render action: 'show', status: :created, location: admin_publication_path(@publication) }
      else
        format.html { render action: 'new' }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_path(@publication), notice: 'Publication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to admin_publications_url }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:title, :content, :thumbnail)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def welcome
    @publication = Publication.first
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController

  def index
    @publications = Publication.all
  end

  def show
    @publication = Publication.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/admin/publications/_form.html.haml
= form_for [:admin, @publication] do |f|
  - if @publication.errors.any?
    #error_explanation
      %h2= "#{pluralize(@publication.errors.count, "error")} prohibited this publication from being saved:"
      %ul
        - @publication.errors.full_messages.each do |msg|
          %li= msg

  .field
    .publication-thumbnail
      = image_tag @publication.thumbnail if @publication.thumbnail?
    = f.label :thumbnail
    = f.file_field :thumbnail

  .field
    = f.label :title
    = f.text_field :title, placeholder: "Title"
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/admin/publications/edit.html.haml
%h1 Editing publication

= render 'form'

= link_to 'Show', admin_publication_path(@publication)
\|
= link_to 'Back', admin_publications_path

app/views/admin/publications/new.html.haml
.container.admin
  %h1 New publication

  = render 'form'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Voleurs de Swing
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header#page-header
      .container
        = link_to image_tag("logo.png", class: "logo"), root_path
    = yield
    %footer#page-footer
      = image_tag "syldave_logo.jpg"
      = image_tag "hehopok_logo.jpg"
      = image_tag "webvds_logo.png"
      = image_tag "autre_logo.jpg"
      = image_tag "igloo_logo.jpg"
    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/pages/welcome.html.haml
#banner
  = image_tag "album.png"
#last-publication
  .container
    = image_tag "last_publication_text.png", id: "last-publication-text"
    - if @publication
      = render "publications/publication", publication: @publication
      %menu#view-all-publication
        = link_to ">> View all publications", publications_path

    - else
      %p No publication publied yet.

app/views/publications/_publication.html.haml
%article
  %menu
    = link_to "Edit", edit_admin_publication_path(publication)
    = link_to "Destroy", admin_publication_path(publication), method: :delete, confirm: "Are you sure ?"
  %header
    .publication-thumbnail= image_tag publication.thumbnail if publication.thumbnail?
    %h1= link_to publication.title, publication
    .publication-date= publication.created_at.to_formatted_s(:long_ordinal)
  = publication.to_html

app/views/publications/index.html.haml
.container
  %menu
    = link_to "Add a new publication", new_admin_publication_path
  = render @publications

app/views/publications/show.html.haml
= render @publication

.container
  %menu
    = link_to "View all publications", publications_path